services:
  pihole:
    container_name: pihole
    image: "pihole/pihole:${TAG:-latest}"
    ports:
      - "8080:80/tcp"
    environment:
      TZ: 'America/Chicago'
      FTLCONF_webserver_api_password: test
    cap_add:
      - NET_ADMIN
      - CAP_SYS_TIME
    restart: unless-stopped
