name: Lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'examples/**'
      - 'templates/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'examples/**'
      - 'templates/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          args: --timeout 10m0s
